greenplum-db/gporca

CMakeLists.txt
Makefile
libnaucrates/src/exception.cpp

This eliminates the unnecessary difference in output depending on whether
a query is planned with ORCA or the Postgres planner. Which is good for
keeping regression tests simple.

Change spelling of error message to match corresponding PostgreSQL message.

---

CMakeLists.txt
Makefile
data/dxl/minidump/Insert-AO-Partitioned-SortDisabled.mdp
data/dxl/minidump/Insert-AO-Partitioned.mdp
data/dxl/minidump/Insert-AO.mdp
data/dxl/minidump/Insert-Parquet-Partitioned-SortDisabled.mdp
data/dxl/minidump/Insert-Parquet-Partitioned.mdp
data/dxl/minidump/Insert-Parquet.mdp
data/dxl/parse_tests/q57-DMLDelete.xml
data/dxl/parse_tests/q58-DMLInsert.xml
data/dxl/parse_tests/q60-DMLUpdate.xml
libgpopt/include/gpopt/operators/CPhysicalDML.h
libgpopt/src/operators/CPhysicalDML.cpp
libgpopt/src/translate/CTranslatorExprToDXL.cpp
libnaucrates/include/naucrates/dxl/operators/CDXLPhysicalDML.h
libnaucrates/include/naucrates/dxl/parser/CParseHandlerPhysicalDML.h
libnaucrates/include/naucrates/dxl/xml/dxltokens.h
libnaucrates/src/operators/CDXLPhysicalDML.cpp
libnaucrates/src/parser/CParseHandlerPhysicalDML.cpp
libnaucrates/src/xml/dxltokens.cpp

In this PR, optimizer adds a field (NeedsSort) in the DMLInsert node indicating if the operator expects the data to be sorted on the partition id or not. 
@vraghavan78 @xinzweb @oarap 
Please take a look.

Add inputSorted attribute to CPhysicalDML

---

CMakeLists.txt

This reduce a 4min clean build to less than 20 seconds (after `make clean`)
```
real	0m14.609s
user	0m17.162s
sys	0m20.762s
```

Enable ccache to speedup cmake

---

libgpopt/src/minidump/CMinidumperUtils.cpp

Reset metadata cache between tests
Release memory to avoid memory leak

Fix CMinidumperUtils to properly disable 105000 [#116803217]

---

CMakeLists.txt
Makefile
data/dxl/minidump/CTE-with-random-filter.mdp
libgpopt/include/gpopt/operators/CPredicateUtils.h
libgpopt/include/gpopt/operators/CScalarFunc.h
libgpopt/src/operators/CExpressionPreprocessor.cpp
libgpopt/src/operators/CPredicateUtils.cpp
libgpopt/src/operators/CScalarFunc.cpp
libnaucrates/include/naucrates/md/IMDFunction.h
server/src/unittest/gpopt/minidump/CCTETest.cpp

Fix predicate propagation into CTE Producer for volatile functions
When predicate has volatile function like random(), the predicate shouldn't be pushed inside CTE producer, since it will change the query semantic.

Fix issue with volatile function doesn't work correctly inside the 'WITH' clause

---

CMakeLists.txt
Makefile
data/dxl/minidump/OneSegmentGather.mdp
libgpopt/src/translate/CTranslatorExprToDXL.cpp
server/src/unittest/gpopt/minidump/CICGTest.cpp

This patch checks the validity of GatherMotion nodes in plans to ensure that we either:
0. Generate a valid Gather node; or
0. Fallback to planner we the plan contains an invalid Gather which has only 1 input segments
This patch should stop the system from crashing in this case.

Fallback when we generate invalid GatherMotion in plans

---

concourse/pipeline.yml

This change enables to ORCA pipeline to publish GPOS binaries and releases to GPOS repo. This change needs to go in together with greenplum-db/gpos#23
@d, @oarap and @hsyuan

Publish Github release for GPOS [#115977749]

---

data/dxl/minidump/OneSegmentGather.mdp
server/src/unittest/gpopt/minidump/CICGTest.cpp

This patch replaces double dashes with C-style comments in the XML
comments. Otherwise our tests would be passing for the wrong reason: we
expect ORCA to fallback in the form of throwing an exception, but we
were giving it a pass for blowing up during XML parsing.
This corrects a subtle bug introduced in 978a927 as part of #46

Correct minidump for #46

---

concourse/pipeline.yml
concourse/publish_tag.bash
concourse/publish_tag.yml

This patch publishes orca source tarball, debug and release binaries, as well as
release tags through the concourse pipeline.
@xinzweb @oarap @vraghavan78 
Please take a look.

[#117367069] Publish GPORCA github release packages through concourse

---

concourse/pipeline.yml

Removed the `secondary` from the group `all` to cut down on the clutter in the `all` view of Concourse. `secondary` has been renamed to `platforms` because its purpose is to build and test on different platforms, but different from the pipeline all, which is used for the ICG. 
Non-centos platform builds and tests were moved to the `platforms` group.
Fixed a source dependency to `build_gpdb_centos6` and also `orca_centos5_release`.

Remove 'secondary' clutter from concourse pipeline. [#119779501]

---

libgpopt/src/translate/CTranslatorExprToDXL.cpp
server/src/unittest/gpopt/minidump/CICGTest.cpp

@vraghavan78 @d @oarap 
There are two commits.
First one, fixed the wrong error major/minor number used for this DXL validation error.
Second commit, fixed the unittest framework so that we can verify the negative test cases with expected exceptions. So that, we can capture such missed cases where we failed the DXL translation due to different exception.

118865569 fix wrong error message when produced a wrong plan with Gather with more than one segments.

---

concourse/pipeline.yml

This, in conjunction with greenplum-db/gpdb#832 , will help us highlight `installcheck-good` failures by providing the `regression.diffs` file for posterity

Copy `regression.diffs` after ICG failure [#120858343]

---

CMakeLists.txt
libgpdbcost/CMakeLists.txt
libgpopt/CMakeLists.txt
libnaucrates/CMakeLists.txt

We still default to shared libraries, but you can use the
"cmake -DBUILD_SHARED_LIBS=off" option to build static libraries instead.

Allow static compilation.

---

data/dxl/minidump/IN-ArrayCmp.mdp
data/dxl/minidump/NOT-IN-ArrayCmp.mdp
libgpopt/include/gpopt/base/CConstraint.h
libgpopt/include/gpopt/base/CConstraintInterval.h
libgpopt/include/gpopt/base/CRange.h
libgpopt/include/gpopt/base/CUtils.h
libgpopt/include/gpopt/operators/CScalarArray.h
libgpopt/src/base/CConstraint.cpp
libgpopt/src/base/CConstraintInterval.cpp
libgpopt/src/base/CRange.cpp
libgpopt/src/base/CUtils.cpp
libgpopt/src/operators/CScalarArray.cpp
libnaucrates/include/naucrates/traceflags/traceflags.h
server/include/unittest/gpopt/CTestUtils.h
server/include/unittest/gpopt/base/CConstraintTest.h
server/src/unittest/CTestUtils.cpp
server/src/unittest/gpopt/base/CConstraintTest.cpp
server/src/unittest/gpopt/operators/CExpressionPreprocessorTest.cpp

ORCA propagates filters across joins when the filter is applied to a join key. In essence, 
```SQL
-- (1)
SELECT * FROM foo, bar WHER foo.id = bar.id AND bar.id IN (1, 20);
```
is equivalent to
```SQL
-- (2)
SELECT * FROM foo, bar WHER foo.id = bar.id AND bar.id IN (1, 20) AND foo.id IN (1,20);
```
however ORCA **currently expands arrays** meaning that (1) actually is transformed to
```SQL
-- (3)
SELECT * FROM foo, bar WHER foo.id = bar.id AND bar.id IN (1, 20) AND foo.id = 1 OR foo.id = 20;
```
For more background, check out [this document](https://docs.google.com/document/d/1l61eaud_qtC15TZLcAf17dwCZ6hCU1zdS3Q4GfXC_2k/edit#).
Previously, ORCA propagated array IN constraints (x in (1,2,3)) by first expanding them into a disjunction of equality statements (x = 1 OR x = 2 ...). This …

[#125960675] Array Constraint Derivation (Array Pt 1)

---

CMakeLists.txt
Makefile
data/dxl/minidump/IN-ArrayCmp.mdp
data/dxl/minidump/NOT-IN-ArrayCmp.mdp
libgpopt/include/gpopt/base/CConstraint.h
libgpopt/include/gpopt/base/CConstraintInterval.h
libgpopt/include/gpopt/base/CRange.h
libgpopt/include/gpopt/base/CUtils.h
libgpopt/include/gpopt/operators/CScalarArray.h
libgpopt/src/base/CConstraint.cpp
libgpopt/src/base/CConstraintInterval.cpp
libgpopt/src/base/CRange.cpp
libgpopt/src/base/CUtils.cpp
libgpopt/src/operators/CScalarArray.cpp
libnaucrates/include/naucrates/traceflags/traceflags.h
server/include/unittest/gpopt/CTestUtils.h
server/include/unittest/gpopt/base/CConstraintTest.h
server/src/unittest/CTestUtils.cpp
server/src/unittest/gpopt/base/CConstraintTest.cpp
server/src/unittest/gpopt/operators/CExpressionPreprocessorTest.cpp

Fixes a bug in CConstraintInterval involving NULLs
When a CConstraintInterval was constructed using an array containing  CDatumGenericGPDB types we exposed a bug where the comparison logic with NULLS was different between datums which could be evaluated within ORCA.
The fix is straightforward: check for NULL datums in an array when constructing a CConstraintInterval. Set a flag in the CConstraintInterval class and do not add the NULL datum to the data structures inside of the Interval.
Also adds a unit test.
@d and I spent a day trying to find out why we would generate an invalid plan when running part of gp_optimizer from ICG.
```SQL
set optimizer=on;
set optimizer_print_plan=on;
set optimizer_print_optimization_stats=on;
set optimizer_enable_array_derivation=on;
set …
```

Array constraint derivation fix nulls

---

libgpopt/CMakeLists.txt
libgpopt/include/gpopt/base/CDatumSortedSet.h
libgpopt/src/base/CConstraintInterval.cpp
libgpopt/src/base/CDatumSortedSet.cpp

We extracted into a class the logic of constructing an array of datums to feed into the construction of ranges for an interval constraint.
This removes repeated deduplication logic in the creation of `CRange`s.

Extract CDatumSortedSet

---

CMakeLists.txt
Makefile
data/dxl/minidump/DPE-IN.mdp
libgpopt/include/gpopt/base/CConstraintInterval.h
libgpopt/include/gpopt/translate/CTranslatorExprToDXL.h
libgpopt/src/base/CConstraintInterval.cpp
libgpopt/src/operators/CPredicateUtils.cpp
libgpopt/src/translate/CTranslatorExprToDXL.cpp

**This PR commits on top of [Pt 1](https://github.com/greenplum-db/gporca/pull/74)** The last commit is the new commit.
Partition filters are expressions which limit the partitions which GPDB scans when doing a table scan.
Allowing array constraints to be derived on expressions exposed a situation where array constraints propagated to partition filters. Arrays weren't previously handled by the Expression to DXL translator, they were processed into disjunctions just prior to translation. The fix we implemented is twofold:
1.  Allow array expressions to be expanded out into OR expressions during DXL translation. This avoids any error conditions when array expressions appear in partition filters because the DXL translator can successfully translate it. 
2.  Do not expand array expressions in …

[#123259241] Array Constraints Partition Filters (Array Pt 2)

---

CMakeLists.txt
Makefile
server/src/unittest/gpopt/base/CConstraintTest.cpp

Recent versions of GCC will error-out with unused variable messages in cases where variables are only used in DEBUG builds. In one problematic test, switching the asserts to build in retail should solve the issue.
@hlinnaka @d This should solve the compiler issue as a bandaid solution.
*Open question*: Shouldn't all asserts in tests compile into retail? I mean, tests are tests and not customer facing.

Changes GPOS_ASSERT to GPOS_RTL_ASSERTS in a Constraint test

---

CMakeLists.txt
Makefile
libgpopt/include/gpopt/operators/CExpressionPreprocessor.h
libgpopt/src/operators/CExpressionPreprocessor.cpp
server/include/unittest/gpopt/CTestUtils.h
server/include/unittest/gpopt/operators/CExpressionPreprocessorTest.h
server/src/unittest/CTestUtils.cpp
server/src/unittest/gpopt/operators/CExpressionPreprocessorTest.cpp

Adds an expression preprocessing stage to convert applicable expressions into array IN or NOT IN expressions. This creates more succinct expression trees and reduces redundancy in final expression output.
Therefore an expression like `x = 1 OR x = 2` should be converted into the equivalent `x IN (1,2)`.
This feature works by doing a recursive walk of the expression tree which looks for multiple AND or OR children which are either array expressions or ScalarComparison children. It then converts them into Constraints. Constraints hold logic to detect redundancy and also to convert OR/AND statements into array statements (Array Pt 1).
We chose to put this method after step 8 of expression preprocessing because step 9 will propagate constraints, and therefore it makes sense to propagate array …

[#125960675] Preprocessing stage for Array Conversion

---

data/dxl/minidump/DPE-NOT-IN.mdp
data/dxl/minidump/DynamicIndexScan-Heterogenous-UnsupportedPredicate.mdp
data/dxl/minidump/Part-Selection-IN.mdp
data/dxl/minidump/Part-Selection-NOT-IN.mdp
data/dxl/minidump/PartTbl-ArrayIn.mdp
data/dxl/minidump/PartTbl-ComplexPredicate1.mdp
data/dxl/minidump/PartTbl-ComplexPredicate4.mdp
data/dxl/minidump/PartTbl-Disjunction.mdp
data/dxl/minidump/PartTbl-NEqPredicate.mdp
data/dxl/minidump/Tpcds-10TB-Q37-NoIndexJoin.mdp

This adds the traceflag for `ArrayConstraints` and fixes the resulting plans. Changes to plans are mainly in `PrintableFilter` element (OR->Array), but also in some `Filter` elements (OR->Array).
Also the constant's ordering in `ScalarArray` element (now sorted).

[#123259241] fix array paritition tests

---

CMakeLists.txt
Makefile
data/dxl/minidump/UnnestSQJoins.mdp
libgpopt/src/operators/CExpressionPreprocessor.cpp

We ran into cases where the preprocessor step 'PexprConvert2In' would
try to create a constraint but fail and get a null value returned to it,
which would cause ORCA to crash. This was because the constraints
framework can only create constraints on certain types. By adding an
additional check for constrainable types we guarantee that a constraint
will be returned.
Also added an ASSERT to check for this condition.

[#128239337] Fix constraint bug in preprocessor

---

CMakeLists.txt
Makefile
data/dxl/minidump/DynamicIndexGet-OuterRefs.mdp
data/dxl/minidump/NullIf-With-Subquery.mdp
data/dxl/minidump/ProjectCountStar.mdp
data/dxl/minidump/ScalarSubqueryCountStar.mdp
data/dxl/minidump/SubqueryNoPullUpTableValueFunction.mdp
data/dxl/minidump/TVF-With-Deep-Subq-Args.mdp
data/dxl/minidump/UnnestSQJoins.mdp
libgpopt/src/xforms/CSubqueryHandler.cpp
server/src/unittest/gpopt/minidump/CAggTest.cpp

Given DDL
```
CREATE TABLE foo (a, b) AS SELECT i,i FROM generate_series(1,1) AS t(i) DISTRIBUTED BY(a);
CREATE TABLE bar (c int, d int);
```
And a query
```
SELECT (SELECT COUNT(*) FROM bar GROUP BY c LIMIT 1) FROM foo;
```
ORCA used to generate a plan that coalesces the result of `count` to
zero. This was wrong. The wrong result looks like this:
```
?column?
----------
0
(1 row)
```
And the portion of the code that adds the `coalesce`
was difficult to understand and we found no test case to justify it.
The expected result should be like this:
```
?column?
----------
(1 row)
```
This commit replaces the `coalesce` with a identity projection. This is
still ugly because we are generating a superfluous `project` operator,
but it is at least correct.
We may follow up with a clean up that …

Do not coalesce if count is not generated by quantified subqueries

---

CMakeLists.txt
Makefile
libgpopt/src/translate/CTranslatorExprToDXL.cpp

When the number of actual segments is 1 and optimizer_segments is set to something greater than 1, orca fallbacks to planner with no reason. The check that causes the fallback should be corrected by checking if the input segments of the Gather matches the actual number of segments.
The issue has been fixed in this PR.

Do not validate Gather Motion based on optimizer_segments [#129012817]

---

CMakeLists.txt
Makefile
data/dxl/minidump/PartTbl-DPE-Correlated-NLOuter.mdp
libgpopt/src/translate/CTranslatorExprToDXL.cpp
libnaucrates/include/naucrates/dxl/operators/CDXLPhysicalAbstractBitmapScan.h
libnaucrates/include/naucrates/dxl/operators/CDXLPhysicalDynamicTableScan.h
server/src/unittest/gpopt/minidump/CPartTblTest.cpp

When the outer child of correlated nest loop join is a partition table,
and it has predicate on the partition key, Orca generated plan with
dynamic partition selector and scan for the outer child, however while
translating plan expression to DXL ORCA always assumed that the outer child
is a relation instead of physical sequence, which caused Orca to replace
the partition selector with filter.
Here is an example to reproduce the issue:
```sql
create table t2(c int, d int);
create table h(j int, i int) DISTRIBUTED BY (i) PARTITION by RANGE(j) (START (1) END (3) EVERY (1));
select (select h.i from t2) from h where h.j = 1;
```
This issue has been fixed in this patch and relevant tests are added.

Don't replace filter child when the correlated outer is sequence while translating expr to dxl

---

CMakeLists.txt
Makefile
data/dxl/minidump/CJoinOrderDPTest/DisableDPJoinOrderForLargeArity.mdp
libgpopt/include/gpopt/engine/CHint.h
libgpopt/src/xforms/CXformUtils.cpp
libnaucrates/include/naucrates/dxl/xml/dxltokens.h
libnaucrates/src/CDXLUtils.cpp
libnaucrates/src/parser/CParseHandlerHint.cpp
libnaucrates/src/xml/dxltokens.cpp
server/CMakeLists.txt
server/include/unittest/gpopt/minidump/CJoinOrderDPTest.h
server/src/startup/main.cpp
server/src/unittest/gpopt/minidump/CJoinOrderDPTest.cpp

CXformExpandNAryJoinDP uses dynamic programming (DP). It is an expensive transformation when the number of join children is more than 10 since computes all the subsets and join orders for
large number of tables.
In this commit we added a hint that sets a hard-limit on how many joins we want to consider in the `CXformExpandNAryJoinDP` rule.
-- Venky and Ivan

Hint to disable CXformExpandNAryJoinDP when join has large number of children [#121181555]

---

CMakeLists.txt
Makefile
data/dxl/minidump/CastOnSubquery.mdp
data/dxl/minidump/Coalesce-With-Subquery.mdp
data/dxl/minidump/DML-Replicated-Input.mdp
data/dxl/minidump/DMLCollapseProject.mdp
data/dxl/minidump/Lead-Lag-WinFuncs.mdp
data/dxl/minidump/PartTbl-DPE-WindowFunction.mdp
data/dxl/minidump/PartTbl-WindowFunction.mdp
data/dxl/minidump/Preds-Over-WinFunc2.mdp
data/dxl/minidump/Select-Proj-OuterJoin.mdp
data/dxl/minidump/Subq-NoParams.mdp
libgpopt/src/operators/CPhysicalSequenceProject.cpp

When Window operator has row_number as the window function GPORCA does not generate the
correct distribution request from its child (asking Broadcast motion).
We have had other issues with Window operator requesting Broadcast motion from its child.
To avoid generating the incorrect plan we are disabling such a request till we fully
understand when such a request is guaranteed to be correct.

Remove broadcast motion for physical sequence project [#131569023]

---

CMakeLists.txt
Makefile
data/dxl/minidump/CPhysicalParallelUnionAllTest/ParallelUnion-Insert.mdp
data/dxl/minidump/CPhysicalParallelUnionAllTest/ParallelUnionAllWithNoRedistributableColumns.mdp
data/dxl/minidump/CPhysicalParallelUnionAllTest/ParallelUnionAllWithNotEqualNumOfDistrColumns.mdp
data/dxl/minidump/CPhysicalParallelUnionAllTest/ParallelUnionAllWithSingleNotRedistributableColumn.mdp
data/dxl/minidump/CPhysicalParallelUnionAllTest/TwoHashedTables.mdp
libgpopt/CMakeLists.txt
libgpopt/include/gpopt/base/CDistributionSpec.h
libgpopt/include/gpopt/base/CDistributionSpecHashedNoOp.h
libgpopt/src/base/CDistributionSpecHashed.cpp
libgpopt/src/base/CDistributionSpecHashedNoOp.cpp
libgpopt/src/operators/CPhysicalParallelUnionAll.cpp
libgpopt/src/operators/CPhysicalSerialUnionAll.cpp
server/src/unittest/gpopt/minidump/CPhysicalParallelUnionAllTest.cpp

This commit introduces a new alternative that produces a plan
using a (best-effort) no-op Hash Redistribute motion.
e.g.
```
CREATE TABLE foo (a int, b int) DISTRIBUTED by (a);
CREATE TABLE bar (c int, d int) DISTRIBUTED by (d);
EXPLAIN SELECT a,b FROM foo UNION ALL SELECT c,d FROM bar;
```
The proposed plan here would be:
```
QUERY PLAN
-----------------------------------------------------------------------------------------------------
Gather Motion 3:1  (slice3; segments: 3)  (cost=0.00..906.50 rows=1002176 width=8)
->  Append  (cost=0.00..876.63 rows=334059 width=8)
->  Redistribute Motion 3:3  (slice1; segments: 3)  (cost=0.00..442.95 rows=334059 width=8)
Hash Key: foo.a
->  Table Scan on foo  (cost=0.00..437.98 rows=334059 width=8)
->  Redistribute Motion 3:3  (slice2; segments: 3) …
```

Generate alternative of No-Op Motion under Parallel Union [#130664383]

---

CMakeLists.txt
Makefile
libgpopt/src/mdcache/CMDAccessor.cpp

This causes the incomplete minidump file when the query contains CTAS such as:
```sql
create table foo as
select row_number() over() as row_num, id_col
from bar
distributed by (id_col);
```

Fix bug that system id counter is never incremented during serialization [#131856005]

---

CMakeLists.txt
Makefile
data/dxl/minidump/ConstTblGetUnderSubqUnderProjectNoOuterRef.mdp
data/dxl/minidump/ConstTblGetUnderSubqUnderProjectWithOuterRef.mdp
data/dxl/minidump/ConstTblGetUnderSubqWithNoOuterRef.mdp
data/dxl/minidump/ConstTblGetUnderSubqWithOuterRef.mdp
data/dxl/minidump/Subq-On-OuterRef.mdp
libgpopt/include/gpopt/base/CUtils.h
libgpopt/src/base/CUtils.cpp
libgpopt/src/operators/CExpressionPreprocessor.cpp
server/src/unittest/gpopt/minidump/CICGTest.cpp

This commit introduces a preprocessing feature where there is a scalar
subquery with a single constant table child.
Instead of having the subquery we replace it with a CScalarIdent
Below is the input and output of the sample.
```
+--CScalarSubquery["a" (0)]
|--CLogicalConstTableGet Columns: ["" (18)] Values: [(1)]
```
```
+--CScalarIdent "a" (0)
```

Remove scalar subquery with a single const tbl child[#131019665]

---

CMakeLists.txt
Makefile
data/dxl/minidump/CPhysicalParallelUnionAllTest/FallBackToSerialUnion.mdp
data/dxl/minidump/CPhysicalParallelUnionAllTest/ParallelUnion-ConstTable.mdp
data/dxl/minidump/CPhysicalParallelUnionAllTest/ParallelUnion-Insert.mdp
data/dxl/minidump/CPhysicalParallelUnionAllTest/ParallelUnionAllWithNoRedistributableColumns.mdp
data/dxl/minidump/CPhysicalParallelUnionAllTest/ParallelUnionAllWithNotEqualNumOfDistrColumns.mdp
data/dxl/minidump/CPhysicalParallelUnionAllTest/ParallelUnionAllWithSingleNotRedistributableColumn.mdp
data/dxl/minidump/CPhysicalParallelUnionAllTest/TwoHashedTables.mdp
libgpdbcost/include/gpdbcost/CCostModelGPDB.h
libgpdbcost/src/CCostModelGPDB.cpp
libgpopt/include/gpopt/operators/CPhysicalUnionAllFactory.h
libgpopt/src/operators/CPhysicalUnionAllFactory.cpp
libgpopt/src/xforms/CXformImplementUnionAll.cpp
server/src/unittest/gpopt/minidump/CPhysicalParallelUnionAllTest.cpp

Previously, when `optimizer_parallel_union` GUC is set, we were only
generating plans with `parallel union all` and omitting `serial union
all`. In this commit, we generate plans for both `serial union all` and
`parallel union all`.
In some cases, enforcement framework may not let `parallel union all` to
be part of a plan because of newly introduced distribution specs and
motions it generates. It is better to provide the legacy union all
implementation to be part of the alternatives instead of completely
omitting the alternative.

Enable both unions in the search space, favor parallel union 130121327

---

CMakeLists.txt
Makefile
libnaucrates/include/naucrates/exception.h
libnaucrates/src/exception.cpp

We changed `ExmiWarningAsError to ExmiOptimizerError`. This is based on the comments from PR : https://github.com/greenplum-db/gpdb/pull/1247
@oarap @xinzweb Please take a look when you get the chance.

Change ExmiWarningAsError to ExmiOptimizerError.

---

CMakeLists.txt
Makefile
libgpopt/src/xforms/CXformUtils.cpp
libnaucrates/src/CDXLUtils.cpp
libnaucrates/src/operators/CDXLOperatorFactory.cpp
server/src/unittest/dxl/CParseHandlerTest.cpp
server/src/unittest/gpopt/operators/CExpressionPreprocessorTest.cpp

gporca has a set of banned API calls which needs to be allowed with the
ALLOW_xxx macro in order for gpopt to compile. But it should be the
library caller(GPDB/Orca)'s resposibility to take care of the function call.
see discussions on greenplum-db/gpdb#1136
and https://groups.google.com/a/greenplum.org/forum/#!topic/gpdb-dev/Mcw6JPav6h4

Remove whole banning mechanism from gporca [#133570595]

---

CMakeLists.txt
Makefile
data/dxl/minidump/CPhysicalParallelUnionAllTest/RandomDistributedChildrenUnhashableColumns.mdp
libgpopt/CMakeLists.txt
libgpopt/include/gpopt/base/CDistributionSpec.h
libgpopt/include/gpopt/base/CDistributionSpecStrictRandom.h
libgpopt/src/base/CDistributionSpecRandom.cpp
libgpopt/src/base/CDistributionSpecStrictRandom.cpp
libgpopt/src/operators/CStrictHashedDistributions.cpp
server/src/unittest/gpopt/minidump/CPhysicalParallelUnionAllTest.cpp

Parallel Union currently has 2 optimization request. The second request is not satisfied
when the children of the parallel union are randomly distributed.
For the first request, if the output columns are not hashable columns the
`CPhysicalParallelUnion` requires random distribution. Since the children are randomly
distributed the `CPhysicalTableScan` already satisfied the optimization request and no
motion is created on top of `CPhysicalTableScan`.
To overcome this issue and enforce a `CPhysicalMotionRandom`, we introduce a new distribution
spec called `CDistributionSpecRandomStrict`. This distribution spec is requested replaces
regular `CDistributionSpecRandom` in the first optimization request where no output column is
redistributable.
Below is the output after this commit:
```
explain …
```

Insert random motion for randomly distributed children for parallel append [#133978027]

---

data/dxl/minidump/DonotPushPartConstThruLimit.mdp
libgpopt/include/gpopt/operators/CPhysical.h
libgpopt/src/operators/CPhysical.cpp
libgpopt/src/operators/CPhysicalAgg.cpp
libgpopt/src/operators/CPhysicalLimit.cpp
libgpopt/src/operators/CPhysicalSequenceProject.cpp
libgpopt/src/operators/CPhysicalSort.cpp
server/src/unittest/gpopt/minidump/CPartTblTest.cpp

The bug is in derivation of required partition propagation specification from the child. Before this fix, we were pushing the partition constraints below Limit which will return wrong results.
To illustrate consider the following table schema and data:
```sql
create table h(j int, i int) DISTRIBUTED BY (i) PARTITION by RANGE(j) (START (1) END (3) EVERY (1));
insert into h values (1,1);
insert into h values (2,2);
insert into h values (2,2);
```
SQL in question is:
```
select * from (select * from h order by j limit 2) x where j = 2;
```
With Planner:
** As you can see from the explain the condition `j = 2` is not pushed below the limit
```sql
vraghavan=# set optimizer = off;
SET
vraghavan=# select * from (select * from h order by j limit 2) x where j = 2;
j | i
---+---
2 | 2
(1 row) …
```

Filters above limit should not pushed down into a partition selector in subquery with limit clause [#133827909]

---

CMakeLists.txt
Makefile
data/dxl/minidump/DQA-KeepOuterReference.mdp
data/dxl/minidump/GroupByOuterRef.mdp
libgpopt/src/operators/CExpressionPreprocessor.cpp
server/src/unittest/gpopt/minidump/CAggTest.cpp

In general, it's beneficial to remove outer references from groupby,
because this value is always a constant for subquery. For example:
```
select a from t where c in (select count(s.j) from s group by s.i, t.b)
```
The `t.b` can be removed safely from above SQL statement, because for
every execution of IN subquery, the `t.b` is constant.
However, this is an issue if the outer reference is the only groupby
column and there is NO additional aggregate functions used. For example:
```
select a from t where c in (select distinct t.b from s)
```
The above statement cannot be further simplified because the rewritten
query below after removing outer reference is invalid:
```
select a from t where c in (select distinct ??? from s)
```
Hence, we add additional validation in pre-processing to …

Fixed outer references in groupby columns [#134091245]

---

concourse/pipeline.yml

The gpdb/concourse repo is getting cleaned up (https://github.com/greenplum-db/gpdb/pull/1334). This commit fixes paths for consumed files that are getting moved.
[#134241435]

Use new paths from GPDB repo

---

data/dxl/minidump/InferPredicatesForLimit.mdp
data/dxl/minidump/PushGbBelowJoin-NegativeCase.mdp
libgpopt/src/operators/CExpressionPreprocessor.cpp
server/src/unittest/gpopt/minidump/CICGTest.cpp

Under situation where there is a subquery under limit and also the
columns used by the predicates inside the subquery are also referenced
outside the subquery, then `InferPredicates` under `PexprPreprocess` will
stop producing predicates under limit.
For example:
```
explain select 1 from (select * from foo where a = 1 and b = a limit 1) x;
QUERY PLAN
------------------------------------------------------------------------------------------------
Result  (cost=0.00..431.00 rows=1 width=4)
->  Result  (cost=0.00..431.00 rows=1 width=1)
Filter: a = 1 AND b = 1
->  Limit  (cost=0.00..431.00 rows=1 width=8)
->  Gather Motion 1:1  (slice1; segments: 1)  (cost=0.00..431.00 rows=1 width=8)
->  Table Scan on foo  (cost=0.00..431.00 rows=1 width=8)
Filter: a = 1 AND a = b
Settings:  optimizer=on …
```

push filter under limit [#129871531]

---

CMakeLists.txt
Makefile
data/dxl/minidump/CPhysicalParallelUnionAllTest/FallBackToSerialAppend.mdp
data/dxl/minidump/CPhysicalParallelUnionAllTest/NoOpMotionUsesOnlyGroupOutputColumns.mdp
data/dxl/minidump/CPhysicalParallelUnionAllTest/ParallelAppend-ConstTable.mdp
data/dxl/minidump/CPhysicalParallelUnionAllTest/ParallelAppend-Insert.mdp
data/dxl/minidump/CPhysicalParallelUnionAllTest/ParallelUnionAllWithNoRedistributableColumns.mdp
data/dxl/minidump/CPhysicalParallelUnionAllTest/ParallelUnionAllWithNotEqualNumOfDistrColumns.mdp
data/dxl/minidump/CPhysicalParallelUnionAllTest/ParallelUnionAllWithSingleNotRedistributableColumn.mdp
data/dxl/minidump/CPhysicalParallelUnionAllTest/RandomDistributedChildrenUnhashableColumns.mdp
data/dxl/minidump/CPhysicalParallelUnionAllTest/RedundantMotionParallelUnionAll.mdp
data/dxl/minidump/CPhysicalParallelUnionAllTest/TwoHashedTables.mdp
libgpopt/include/gpopt/operators/CPhysicalMotionHashDistribute.h
libgpopt/src/base/CDistributionSpecHashedNoOp.cpp
libgpopt/src/operators/CPhysicalMotionHashDistribute.cpp
server/src/unittest/gpopt/minidump/CPhysicalParallelUnionAllTest.cpp

Before no-op motions were introduced, a hash-redistribute motion was
intended to really move tuples around, and it was justifiable that they
required 'ANY' distribution, and hence they shared optimization contexts
when everything else were identical.
A no-op motion, however, was intended to _not_ move tuples. i.e. A no-op
motion to hash-redistribute by column `b` on top of a relation that's
hash-distributed on column `a` is not only undesirable, it's completely
unintended. To rule out such plans, we made hash-redistribute motions a
bit more intelligent when their distribution specifications say `no-op`:
they should require the relation under them to be distributed exactly as
the motions (as opposed to `ANY`).
A nice side-effect of this change is, no-op motions that distribute on
columns …

No-Op Motion requires distribution of relational child

---

data/dxl/minidump/DisableLargeTableBroadcast.mdp
data/dxl/minidump/HAWQ-TPCH-Stat-Derivation.mdp
data/dxl/minidump/Tpcds-10TB-Q37-NoIndexJoin.mdp
data/dxl/minidump/Tpcds-NonPart-Q70a.mdp
libgpdbcost/src/CCostModelGPDB.cpp
libgpopt/include/gpopt/engine/CHint.h
libnaucrates/include/naucrates/dxl/xml/dxltokens.h
libnaucrates/src/CDXLUtils.cpp
libnaucrates/src/parser/CParseHandlerHint.cpp
libnaucrates/src/xml/dxltokens.cpp
server/src/unittest/gpopt/minidump/CICGTest.cpp

Added a guc, `optimizer_large_table_broadcast` to set the threshold on maximum number of rows to broadcast.
```
QUERY PLAN
-----------------------------------------------------------------------------------------------------
Gather Motion 3:1  (slice2; segments: 3)  (cost=0.00..869.16 rows=1 width=16)
->  Hash Join  (cost=0.00..869.16 rows=1 width=16)
Hash Cond: bar.d = foo.a
->  Table Scan on bar  (cost=0.00..431.69 rows=33190 width=8)
->  Hash  (cost=431.02..431.02 rows=100 width=8)
->  Broadcast Motion 3:3  (slice1; segments: 3)  (cost=0.00..431.02 rows=100 width=8)
->  Table Scan on foo  (cost=0.00..431.00 rows=34 width=8)
Settings:  optimizer=on
Optimizer status: PQO version 1.694
```
If we set the guc to a value lower than the row count such `set optimizer_large_table_broadcast to …

New hint to penalize broadcast of large number of rows

---

CMakeLists.txt
libgpopt/version.h.in

We bumped the GPORCA version to 2.0 after merging GPOS with GPORCA.
Cmake undefs the GPORCA_VERSION_MINOR when the minor number is 0. 0 is
considered as a false constant by cmake.
In gpdb, use GPORCA_VERSION_STRING instead of separate GPORCA_VERSION_MAJOR
and GPORCA_VERSION_MINOR.

Update Version number macros

---

CMakeLists.txt

This patch adds a `.0` (or as they call it over semver.org, the "patch"
number) to our version. This makes our version semver-compliant. It also
makes it abundantly clear that our version number (say `2.1.0`) is not a
decimal floating point number. ("What is newer? 2.2 or 2.19?")
N.B. our practice is only bumping the minor and major version numbers.
This change doesn't not signal a change in that practice.
I'm also hiding this commit from CI so that it only impacts the next
push (so it will be, say, `2.2.0` if we are currently on `2.1`).
[ci skip]

Append `.0` to version string

---

CMakeLists.txt
cmake/FindAtomics.cmake
libgpos/CMakeLists.txt
libgpos/config.h.in

Commmit 76af81942a, to generate a config.h with all the required GPOS_*
flags that affect the API of the resulting binaries, most notably
GPOS_DEBUG, was broken. It didn't derive the GPOS_DEBUG flag from
from CMAKE_BUILD_TYPE sit should've. It did the right thing if you set
"GPOS_DEBUG=1" property on the cmake command line, but that property was
not set automatically with CMAKE_BUILD_TYPE=Debug. CMAKE_BUILD_TYPE=Debug
added GPOS_DEBUG=1 to the COMPILE_DEFINITIONS property, but that's different
from having a stand-along GPOS_DEBUG property.
Likewise, the GPOS_<arch> and GPOS_32BIT/64BIT variables were also not set
correctly. The reason I didn't notice this while testing was that the
flags in COMPILE_DEFINITIONS were still set, even though if config.h was
generated correctly, those would …

Fix populating config.h.

---

libgpopt/CMakeLists.txt
libgpopt/include/gpopt/base/CColConstraintsArrayMapper.h
libgpopt/include/gpopt/base/CColConstraintsHashMapper.h
libgpopt/include/gpopt/base/CConstraint.h
libgpopt/include/gpopt/base/IColConstraintsMapper.h
libgpopt/src/base/CColConstraintsArrayMapper.cpp
libgpopt/src/base/CColConstraintsHashMapper.cpp
libgpopt/src/base/CConstraint.cpp
libgpopt/src/base/IColConstraintsMapper.cpp

GP Orca rearranges constraints list where a constrint only refers a single
column reference as much as possible. In order to do that the previous implementation
traverse the list for every single constraint and that results in O(n^2) (quadratic)
running time.
If the number of constraints in the list is higher than some threashold
(hardcoded as 5 for now) it results in significant performance degredation.
This commit uses hash map to create a map from column referances to constraints where
a constraint only refers a single column. This will reduce the quadratic running time
of deduplication process to a linear running time. However, creating a hashmap for short
list of constraints also results in performnce degradation.

[#139042295] Dedup constraints in linear time

---

data/dxl/expressiontests/CScalarConstArray.xml
libgpopt/include/gpopt/base/CUtils.h
libgpopt/include/gpopt/operators/CScalarArray.h
libgpopt/src/base/CConstraint.cpp
libgpopt/src/base/CConstraintInterval.cpp
libgpopt/src/base/CDatumSortedSet.cpp
libgpopt/src/base/CUtils.cpp
libgpopt/src/operators/CPredicateUtils.cpp
libgpopt/src/operators/CScalarArray.cpp
libgpopt/src/operators/CScalarArrayCmp.cpp
libgpopt/src/translate/CTranslatorDXLToExpr.cpp
libgpopt/src/translate/CTranslatorExprToDXL.cpp
libnaucrates/src/statistics/CStatsPredUtils.cpp
server/include/unittest/gpopt/translate/CTranslatorDXLToExprTest.h
server/src/unittest/gpopt/translate/CTranslatorDXLToExprTest.cpp

This is a new approach to achieve the cleaner code for the previous pull request.
Instead of creating a new operator, `CScalarArray` is updated and utility functions are created to consume new operator's features in the codebase. The collapsed constants are stored in the `CScalarArray` in itself. 
"When there is large number of values in the array or IN list, Orca spent a lot of time on optimization. The reason is that every const item in the array is used to create a group and group expression in the MEMO structure. For scalar const values in the array, it is not necessary to create the MEMO group for it. We create a new scalar operator CScalarConstArray to treat the constant values in the children expression as its attribute, which avoids the MEMO group creation for constant values to …

132930893 large in new

---

libgpos/include/gpos/common/CHashMap.h
libgpos/include/gpos/common/CHashMap.inl
libgpos/include/gpos/common/CHashMapIter.h
libgpos/include/gpos/common/CHashMapIter.inl

Currently, the HashMapIter implementation scans through all hash map
buckets to get the next existing hash chain. This degrades performance
significantly.
This commit improves the iterator implementation by maintaining a
dynamic key array which holds the existing keys in HashMap. The
iteration is done using this array.

[#141511349] Improve HashMap iterator implementation

---

libgpopt/include/gpopt/base/CCTEReq.h

We do not need to call FSubset() twice to check for equality.
Two CTE requirements will be considered equal if their lengths match and
one is subset of the other.

Improve FEqual() in CCTEReq

---

libgpopt/src/search/CGroupExpression.cpp

This is an expensive system call that we should avoid.

Do not record time for transformations when profiling is disabled

---

CMakeLists.txt
data/dxl/minidump/CTEMisAlignedProducerConsumer.mdp
libgpopt/include/gpopt/base/CUtils.h
libgpopt/include/gpopt/exception.h
libgpopt/include/gpopt/optimizer/COptimizer.h
libgpopt/src/base/CUtils.cpp
libgpopt/src/exception.cpp
libgpopt/src/optimizer/COptimizer.cpp
server/src/unittest/gpopt/minidump/CICGTest.cpp

This PR introduces a check to detect if the CTE producer and
matching consumer is executed on the right place. So if CTE producer is
executed on master/segments/segment, then matching consumer also has to
execute on master/segments/segment. In rare cases, orca generates plans
that violate this assumption. This PR detects plans of that kind and
falls back.

[#146190079] ORCA falls back due to CTE prodocer-consumer inconsistency

---

concourse/check_existing_tag.py
concourse/check_existing_tag.yml
concourse/pipeline.yml

Each ORCA commit must BUMP the version. If the version is not bumped new releases will not be pushed to the ORCA repository. This commit adds the check to validate the version of the current commit with the tag version existing on the repository.

Add Check for existing tag before publishing

---

libgpos/server/include/unittest/gpos/common/CAutoPTest.h
libgpos/server/src/unittest/gpos/common/CAutoPTest.cpp

Previous to c09a0ac, `CStackObject()` constructor did a validity check if the pointer is on the stack using `FOnStack()`. Since the function is removed; the following test in `CAutoPTest` is invalid :
CAutoPTest::EresUnittest_Allocation()
This causes test failure in debug build. Hence this commit removes the test.

Fix broken CAutoPTest & make pipeline green

---

server/CMakeLists.txt

This is semantically more precise, and also enables ORCA to be included
in other CMake projects
[ci skip]

Use PROJECT_SOURCE_DIR instead of CMAKE_SOURCE_DIR

---

CMakeLists.txt
README.md
concourse/conanfile.py
libgpopt/src/base/CCTEMap.cpp
libgpopt/src/base/CCTEReq.cpp
libgpopt/src/base/CDrvdProp.cpp
libgpopt/src/base/CDrvdPropCtxt.cpp
libgpopt/src/base/CEnfdProp.cpp
libgpopt/src/base/CPartIndexMap.cpp
libgpopt/src/base/CReqdPropPlan.cpp
libgpos/CMakeLists.txt
libgpos/include/gpos/common/CPrintablePointer.h

A "tautological" comparison is a comparison that's only meaningfully
necessary when we consider "undefined" C++ behaviors.
For context, in well-formed C++ code:
1. references can never be bound to NULL; and
1. the `this` pointer in a member function can never be NULL
Historically ORCA has relied on implementation-specific (undefined,
actually) behavior where
1. we might call a member function on a potentially NULL object with
the `->` operator, or
1. some callers may bind a (possibly-NULL) pointer to a reference with
the '*' operator and try to print it into an IOStream
While doing so gives the benefit of centralizing the check, a dependence
on undefined behavior means we risk producing the wrong code. Indeed,
more modern compilers aggressively optimize against undefined behaviors:
e.g. …

Remove tautological undefined comparisons

---

README.md

1. no more "mkdir ... cd ..."
1. remove leftover mentions of `make` instead of `ninja`
1. remove extraneous instructions of parallelizing the build when Ninja is parallel by default
This also partly addresses #248

Slight README clean up

---

data/dxl/minidump/BitmapIndexProbeMergeFilters.mdp
libgpopt/src/xforms/CXformUtils.cpp
server/src/unittest/gpopt/minidump/CBitmapTest.cpp

There was bug in the way Bitmap Index Probe conditions were being merged.
Consider the table query below :
```sql
SELECT * FROM foo WHERE b = 2 AND c >=6 AND c <= 6;
```
Let's assume there is index on coloumn 'b' and 'c'. Bitmap Index Probe
on second and third condition ('c>=6' and 'c<=6') are mergeable because
they are on the same indexed coloumn. Due to the bug, Orca would merge
third Index Probe with first Index Probe condition ('b=2') instead. This lead to a wrong 'Recheck
Condition' which if selected as a filter lead to a wrong plan. This
commit fixes this bug.
Signed-off-by: Jesse Zhang <sbjesse@gmail.com>

Merge conditions into corresponding Bitmap Index Probes

---

data/dxl/minidump/JoinOptimizationLevelQuery3WayHashJoinPartTbl.mdp
libgpopt/src/operators/CPhysicalHashJoin.cpp
libgpopt/src/operators/CPhysicalInnerHashJoin.cpp
server/src/unittest/gpopt/minidump/CJoinOrderDPTest.cpp

Push Partition Request to join child assuming no DPE
Consider a query of the form as below joining 1 partitioned table (p1) with other non partitioned table (foo):
```sql
set optimizer_join_order=query;
create table p1(a int, b int) partition by range(b) (start (1) end (2) every (1));
create table foo (a int, b int);
create table bar (a int, b int);
select disable_xform('CXformInnerJoin2NLJoin');
explain select * from p1, foo where p1.b = foo.b;
```
The Memo after optimization for the above query is as below:
```
Group 1 (#GExprs: 6):
0: CLogicalGet "foo" ("foo")
1: CPhysicalTableScan "foo"
2: CPhysicalMotionGather(master) [ 1 ]
3: CPhysicalPartitionSelector, Scan Id: 1, Part Table: (24576,1.0) [ 1 ]
4: CPhysicalMotionBroadcast  [ 1 ]
5: CPhysicalMotionHashDistribute HASHED: [ …
```

Hash Join alternative not being generated for queries involving 3 or more tables (partitioned)

---

libgpopt/src/base/CCostContext.cpp

In `CCostContext.cpp`, the function name in comment should be 'CostCompute' but `ComputeCost`.

Fix a typo in comment.

---

data/dxl/minidump/FullOuterJoin.mdp
data/dxl/minidump/Join-Dist-Key-No-Motion.mdp
libgpopt/include/gpopt/base/CDistributionSpecHashed.h
libgpopt/include/gpopt/base/CUtils.h
libgpopt/src/base/CDistributionSpecHashed.cpp
libgpopt/src/base/CUtils.cpp
libgpopt/src/operators/CPhysicalJoin.cpp
server/src/unittest/gpopt/minidump/CICGTest.cpp

For the following query, Orca generated redundant redistribution motion on join
output that is already distributed by join key:
```sql
create table foo(a int, b int, primary key(a));
create table bar(a int, b int, primary key(a));
create table zoo(a int, b int, primary key(a));
explain select * from foo left join bar on foo.a=bar.a left join zoo on zoo.a=bar.a;
QUERY PLAN
-------------------------------------------------------------------------------------------------
Gather Motion 3:1  (slice2; segments: 3)  (cost=0.00..439.00 rows=3 width=24)
->  Nested Loop Left Join  (cost=0.00..439.00 rows=1 width=24)
Join Filter: true
->  Redistribute Motion 3:3  (slice1; segments: 3)  (cost=0.00..437.00 rows=1 width=16)
Hash Key: bar.a
->  Nested Loop Left Join  (cost=0.00..437.00 rows=1 width=16) …
```

Remove redundant motion for hash distributed join relation

---

data/dxl/minidump/LeftJoin-UnsupportedFilter-Cardinality.mdp
libnaucrates/src/statistics/CStatisticsUtils.cpp
server/src/unittest/gpopt/minidump/COuterJoinTest.cpp

If left outer join has a join filter that can't do direct statistics
comparison, like 'varchar cmp int', Orca will aplly the unsupported filter
later on top of join stats, which may result less cardinality. This is OK for
inner or semi join, but not OK for outer join, because for outer join, the
cardinality of LOJ results is always greater or equal with the cardinality of
outer child of LOJ. The issue has been fixed by adding the cardinality guard
check.

Fix wrong cardinality estimation for LOJ with unsupported join filter for stats

---

libgpos/include/gpos/_api.h
libgpos/include/gpos/common/CList.h
libgpos/src/_api.cpp
libgpos/src/test/CUnittest.cpp
server/src/unittest/gpopt/minidump/CAggTest.cpp
server/src/unittest/gpopt/minidump/CBitmapTest.cpp
server/src/unittest/gpopt/minidump/CCTETest.cpp
server/src/unittest/gpopt/minidump/CCastTest.cpp
server/src/unittest/gpopt/minidump/CCollapseProjectTest.cpp
server/src/unittest/gpopt/minidump/CConstTblGetTest.cpp
server/src/unittest/gpopt/minidump/CDMLTest.cpp
server/src/unittest/gpopt/minidump/CDirectDispatchTest.cpp
server/src/unittest/gpopt/minidump/CEscapeMechanismTest.cpp
server/src/unittest/gpopt/minidump/CExternalTableTest.cpp
server/src/unittest/gpopt/minidump/CICGTest.cpp
server/src/unittest/gpopt/minidump/CIndexTest.cpp
server/src/unittest/gpopt/minidump/CMinidumpWithConstExprEvaluatorTest.cpp
server/src/unittest/gpopt/minidump/CMissingStatsTest.cpp
server/src/unittest/gpopt/minidump/COuterJoinTest.cpp
server/src/unittest/gpopt/minidump/CPartTblTest.cpp
server/src/unittest/gpopt/minidump/CPredicateTest.cpp
server/src/unittest/gpopt/minidump/CPruneColumnsTest.cpp
server/src/unittest/gpopt/minidump/CScalarArrayCmpTest.cpp
server/src/unittest/gpopt/minidump/CSemiJoinTest.cpp
server/src/unittest/gpopt/minidump/CSetopTest.cpp
server/src/unittest/gpopt/minidump/CSubqueryTest.cpp
server/src/unittest/gpopt/minidump/CTVFTest.cpp
server/src/unittest/gpopt/translate/CTpchTest.cpp

It is adding a lot of debug test runtime overhead without adding any value.

Remove fEnableExtendedAsserts, which is useless

---

README.md

A GPDB developer who uses CentOS 6 recently requested we add a tip to our README about adding /usr/local/lib to the list of directories in which the program loader looks.

Update README with shared library tip

---

README.md

Add a hint to rebuild the shared library cache if the user follows the suggestion to add the 
usr/local/lib path to /etc/ld.so.conf file.

Suggest additional hint in common issues

---

server/dxl.xsd

I try to generate DXL parser according dxl.xsd in golang, and find some non-compliant issues in this file:
- complexContent should only include (restriction|extension)
- SubPlanTestExpr:  add "dxl:" space prefix

Fix issues in dxl.xsd that didn't meet XSD standard

---

libgpopt/include/gpopt/operators/CLogicalIndexApply.h
libgpopt/include/gpopt/operators/CLogicalJoin.h
libgpopt/src/operators/CLogicalIndexApply.cpp
libgpopt/src/operators/CLogicalJoin.cpp
libnaucrates/include/naucrates/statistics/CHistogram.h
libnaucrates/include/naucrates/statistics/CInnerJoinStatsProcessor.h
libnaucrates/include/naucrates/statistics/CJoinStatsProcessor.h
libnaucrates/include/naucrates/statistics/CLeftAntiSemiJoinStatsProcessor.h
libnaucrates/include/naucrates/statistics/CLeftOuterJoinStatsProcessor.h
libnaucrates/include/naucrates/statistics/CLeftSemiJoinStatsProcessor.h
libnaucrates/include/naucrates/statistics/CStatistics.h
libnaucrates/include/naucrates/statistics/CStatisticsUtils.h
libnaucrates/include/naucrates/statistics/IStatistics.h
libnaucrates/src/statistics/CHistogram.cpp
libnaucrates/src/statistics/CInnerJoinStatsProcessor.cpp
libnaucrates/src/statistics/CJoinStatsProcessor.cpp
libnaucrates/src/statistics/CLeftAntiSemiJoinStatsProcessor.cpp
libnaucrates/src/statistics/CLeftOuterJoinStatsProcessor.cpp
libnaucrates/src/statistics/CLeftSemiJoinStatsProcessor.cpp
libnaucrates/src/statistics/CStatistics.cpp
libnaucrates/src/statistics/CStatisticsUtils.cpp

This PR is a refactor of join stats processing logic out of CStatistics and into separate classes. There are very few logic changes in this PR, so to make it clear where those are for the reviewer, we have called them out here.
Main Re-factor Points:
- Create a new base class, `CJoinStatsProcessor`, into which we move methods from `CStatistics` and `CStatisticsUtils` which process statistics exclusively for joins.
- Create a child class for each join type (corresponding to the logical operator) and move processing methods specific to that type of join into its respective class - e.g. `CInnerJoinStatsProcessor` inherits from `CJoinStatsProcessor` and contains methods which manipulate statistics specific to Inner Joins.
- Because the methods were moved into the `C[join type]StatsProcessor` …

Refactor statistics computation for joins

---

server/include/unittest/gpopt/CTestUtils.h
server/src/unittest/CTestUtils.cpp

Previously, when a test is run as:
`$ ./server/gporca_test -U <>`
we stopped at the first failing minidump, be it a plan space change or
actual plan diff and did not continue with the subsequent minidumps.
This commit changes the behaviour such that we run through all the
minidump tests and do not stop at the first failure. The space size
change or plan change will be displayed in case of each failure. The
advantage is, we can get a quicker and consolidated feedback without
re-running the test after fixing each failing minidump.

Don't stop testing when a minidump test fails

---

concourse/clone_remote_repo.py
concourse/clone_remote_repo.yml
concourse/test_orca_pipeline.yml
concourse/untar_build_and_test.py
concourse/untar_build_and_test_centos5_debug.yml
concourse/untar_build_and_test_centos5_release.yml

This commits adds the pipeline and the related scripts to trigger
the orca ci pipeline, but this pipeline does not produce any github releases for the orca branch tested.
What is remaining:
- Integration with Slack (Will work with toolsmiths for it)
Note: Will change the URL pointing to my repos before merging. But since, there is no dependency on the remaining work, i raised the PR.

Add Pipeline to test specified orca and gpdb branch

---

libgpos/include/gpos/test/CUnittest.h
libgpos/src/test/CUnittest.cpp
server/src/startup/main.cpp

Introduces a new command line argument to gporca_test. When it is set to
something non-zero, it will override the PlanId mentioned in the
minidump file (usually 0). This is useful for enumerating all plans
generated by ORCA easily.
e.g:
for i in $(seq 0 15); do
./server/gporca_test -d $mdp -T 101001 -i $i
done

Override PlanId in minidump with an argument to gporca_test

---

concourse/test_explain_ds_suite_pipeline.yml

This commit add the pipeline yml file for testing a custom GPDB and
GPORCA commit against gpdb/5X_STABLE and gporca/master using 1TB test
suite data to compare plans.
Corresponding GPDB PR: https://github.com/greenplum-db/gpdb/pull/7261

Add pipeline for running explain tests

---

concourse/clone_remote_repo_gpdb4.py
concourse/clone_remote_repo_gpdb4.yml
concourse/test_orca_2x_pipeline.yml

This commits adds the automation required to test gpdb4 and gporca 2x
branches via a pipeline. This will enable orca developers to not fork
their own pipeline and just use it for their testing.
Corresponding PR: https://github.com/pivotal/gp-gpdb4/pull/579

Add concourse pipeline for GPDB4 and ORCA 2X

---

data/dxl/minidump/ConvertBoolConstNullToConstTableFalseFilter.mdp
libgpopt/include/gpopt/base/CUtils.h
libgpopt/src/base/CUtils.cpp
libgpopt/src/operators/CLogicalSelect.cpp
server/CMakeLists.txt

Setup:
create table t1 (a bool);
explain select * from t1 where a = NULL::bool;
before fix:
```
Gather Motion 3:1
->  Seq Scan on bar
Filter: NULL::boolean
```
After fix
```
QUERY PLAN
------------------------------------------------
Result
->  Result
One-Time Filter: false
Optimizer status: PQO version 3.51.0
```
We can convert this to a Const Table Get with false filter.
When we have such a scalar, the max card of the operator will be 0, which
will cause it to be converted to a ConstTableGet with False filter. This commit fixes the max card.

Convert ScalarConst Null filter to ConstTableGet with False Filter

---

concourse/pipeline.yml
concourse/pr_pipeline.yml
concourse/test_explain_pipeline.yml
concourse/test_orca_pipeline.yml

Updated and deployed pipelines:
- https://qpa.ci.gpdb.pivotal.io/teams/main/pipelines/gporca
- https://qpa.ci.gpdb.pivotal.io/teams/main/pipelines/gporca_pr.yml
- https://qpa.ci.gpdb.pivotal.io/teams/main/pipelines/ds_explain_5X
- https://qpa.ci.gpdb.pivotal.io/teams/main/pipelines/index_explain_5X
- https://qpa.ci.gpdb.pivotal.io/teams/main/pipelines/gporca-dev

Convert ORCA pipelines to use Vault variables
